name: em-casing-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - mkl
  - pip:
    - pymatsolver
    - geoana
    - git+https://github.com/simpeg/simpeg.git@feat/dc_fields_derivs
    - git+https://github.com/simpeg-research/casingSimulations.git
